name: Build APK

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Build the APK using Buildozer Action
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          # If your buildozer.spec is in the root, use "."
          # If it is in a subfolder (e.g., "src" or "app"), change the workdir accordingly.
          workdir: .
          buildozer_version: stable

      # Step 3: Upload the generated APK as an artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-package
          path: ${{ steps.buildozer.outputs.filename }}
