name: Build

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository code.
      - name: Checkout
        uses: actions/checkout@v2

      # 2. Build the APK using Buildozer action.
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          # Command to run – by default it runs "buildozer android debug"
          # You can override it by specifying "command: <your command>"
          workdir: test_app
          buildozer_version: stable

      # 3. Upload the generated APK as an artifact.
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
